target-version = "py312"
line-length = 88

[lint]
select = ["E4", "E7", "E9", "F", "B", "BLE001", "PYI034", "RUF012", "TRY004"]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Cookie"]
