"""rewards schema and retention cases

Revision ID: af96e87abaa9
Revises: 0001_initial
Create Date: 2026-09-08 15:35:51.418624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af96e87abaa9'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_reasons', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_cases_client_id'), 'retention_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_retention_cases_club_id'), 'retention_cases', ['club_id'], unique=False)
    op.create_index(op.f('ix_retention_cases_status'), 'retention_cases', ['status'], unique=False)
    op.create_index('uq_open_case_per_client', 'retention_cases', ['client_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('reward_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('budget_month', sa.Date(), nullable=False),
    sa.Column('revenue_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('configured_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('released', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('reserved + spent <= LEAST(configured_limit, revenue_base * 0.04)', name='ck_budget_limit'),
    sa.CheckConstraint('reserved >= 0 AND spent >= 0', name='ck_budget_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'budget_month', name='uq_budget_club_month')
    )
    op.create_table('budget_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('consumed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('consumed_amount <= reserved_amount', name='ck_reservation_consumed'),
    sa.ForeignKeyConstraint(['budget_id'], ['reward_budgets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_budget_reservations_budget_id'), 'budget_reservations', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_reservations_status'), 'budget_reservations', ['status'], unique=False)
    op.create_table('discount_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('applicable_purchase_type', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['budget_reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_discount_grants_client_id'), 'discount_grants', ['client_id'], unique=False)
    op.create_index(op.f('ix_discount_grants_status'), 'discount_grants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_grants_status'), table_name='discount_grants')
    op.drop_index(op.f('ix_discount_grants_client_id'), table_name='discount_grants')
    op.drop_table('discount_grants')
    op.drop_index(op.f('ix_budget_reservations_status'), table_name='budget_reservations')
    op.drop_index(op.f('ix_budget_reservations_budget_id'), table_name='budget_reservations')
    op.drop_table('budget_reservations')
    op.drop_table('reward_budgets')
    op.drop_index('uq_open_case_per_client', table_name='retention_cases', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_retention_cases_status'), table_name='retention_cases')
    op.drop_index(op.f('ix_retention_cases_club_id'), table_name='retention_cases')
    op.drop_index(op.f('ix_retention_cases_client_id'), table_name='retention_cases')
    op.drop_table('retention_cases')
    # ### end Alembic commands ###
