---
deploy_user: reaper
deploy_dir: /home/reaper/base_dir

app_repo: https://github.com/reaper-kia/base_monolit_stucture.git
app_branch: main
app_version: main

app_name: base_structure
app_env: local


postgres_host: db
postgres_port: 5432
postgres_db: base_structure
postgres_user: base_structure

redis_host: redis
redis_port: 6379
redis_db: 0